data_source snowflake:  
    type: snowflake
    account: ax85244.central-india.azure
    username: Balajisanthanam
    password: Bala_ji_2303
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: COMPUTE_WH
    schema: TPCH_SF1
    threads: 10
    client_session_keep_alive: False
soda_cloud:
  host: cloud.soda.io
  api_key_id: d7be935f-4f06-40a1-b77a-f4ec5207f115
  api_key_secret: Br7TazObPMhPXIlC-wJN7axtZiWxojOhBXeCNsT98q4Jc88MKD_owA
 
